### PR TITLE
feat: support nightly

### PR DESCRIPTION
**Pull request by zhyncs**
Subsequent automation will be implemented in flashinfer-nightly, allowing updates via git push.

### CODE REVIEW

**Comment by zhyncs** [comment]
The purpose of this is that sometimes flashinfer makes a hotfix, but because there is no release, if users are in a hurry, they can use the nightly version. cc @yzh119 @merrymercy

**Comment by zhyncs** [comment]
fix https://github.com/flashinfer-ai/flashinfer-nightly/issues/1

**Comment by zhyncs** [comment]
cc @abcdabcd987

**Review by yzh119 — APPROVED** [review]
The index should be update automatically in the future.
Thanks @zhyncs for setting things up!

**Pull request merged**
